In [1]:
import pandas as pd

In [5]:
# código para cargar un archivo parquet desde internet
# necesito cargar datos de todos los meses de 2025, pero por ahora solo cargo el de enero para probar
# url mes enero 2025
url = "https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-01.parquet"
df = pd.read_parquet(url)

In [10]:
df.columns=[columna.lower() for columna in df.columns]
df.head()

,vendorid,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,ratecodeid,pulocationid,dolocationid,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-01-01 00:03:01,2025-01-01 00:17:12,N,1.0,75,235,1.0,5.93,24.70,...,0.5,6.80,0.00,NaN,1.0,34.00,1.0,1.0,0.00,0.0
1,2,2025-01-01 00:19:59,2025-01-01 00:25:52,N,1.0,166,75,1.0,1.32,8.60,...,0.5,0.00,0.00,NaN,1.0,11.10,2.0,1.0,0.00,0.0
2,2,2025-01-01 00:05:29,2025-01-01 00:07:21,N,5.0,171,73,1.0,0.41,25.55,...,0.0,0.00,0.00,NaN,1.0,26.55,2.0,2.0,0.00,0.0
3,2,2025-01-01 00:52:24,2025-01-01 01:07:52,N,1.0,74,223,1.0,4.12,21.20,...,0.5,6.13,6.94,NaN,1.0,36.77,1.0,1.0,0.00,0.0
4,2,2025-01-01 00:25:05,2025-01-01 01:01:10,N,1.0,66,158,1.0,4.71,33.80,...,0.5,7.81,0.00,NaN,1.0,46.86,1.0,1.0,2.75,0.0

In [11]:
#Cambiar nombre de columnas con palabras unidas por guion bajo
df.rename(columns={'vendorid': 'vendor_id', 'ratecodeid': 'rate_code_id', 'pulocationid': 'pu_location_id', 'dolocationid': 'do_location_id'},inplace=True)
df.head()

,vendor_id,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,rate_code_id,pu_location_id,do_location_id,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-01-01 00:03:01,2025-01-01 00:17:12,N,1.0,75,235,1.0,5.93,24.70,...,0.5,6.80,0.00,NaN,1.0,34.00,1.0,1.0,0.00,0.0
1,2,2025-01-01 00:19:59,2025-01-01 00:25:52,N,1.0,166,75,1.0,1.32,8.60,...,0.5,0.00,0.00,NaN,1.0,11.10,2.0,1.0,0.00,0.0
2,2,2025-01-01 00:05:29,2025-01-01 00:07:21,N,5.0,171,73,1.0,0.41,25.55,...,0.0,0.00,0.00,NaN,1.0,26.55,2.0,2.0,0.00,0.0
3,2,2025-01-01 00:52:24,2025-01-01 01:07:52,N,1.0,74,223,1.0,4.12,21.20,...,0.5,6.13,6.94,NaN,1.0,36.77,1.0,1.0,0.00,0.0
4,2,2025-01-01 00:25:05,2025-01-01 01:01:10,N,1.0,66,158,1.0,4.71,33.80,...,0.5,7.81,0.00,NaN,1.0,46.86,1.0,1.0,2.75,0.0

In [29]:
import pandas as pd
import os

"""
Template code for loading data from any source.

    Returns:
        Anything (e.g. data frame, dictionary, array, int, str, etc.)
"""
year = 2025
months = [1, 2]  # Enero y Febrero como prueba

base_columns = None
all_chunks = []

for month in months:
    url = f'https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_{year}-{month:02d}.parquet'
# Leer parquet directamente desde la URL
    df = pd.read_parquet(url)

 
    for chunk in load_parquet_in_chunks(df):
        all_chunks.append(chunk)

        print(f'Mes {month} cargado.')
 
all_chunks# Specify your data loading logic here

Mes 1 cargado.
Mes 2 cargado.

[       VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  \
 0             2  2025-01-01 00:03:01   2025-01-01 00:17:12                  N
 1             2  2025-01-01 00:19:59   2025-01-01 00:25:52                  N
 2             2  2025-01-01 00:05:29   2025-01-01 00:07:21                  N
 3             2  2025-01-01 00:52:24   2025-01-01 01:07:52                  N
 4             2  2025-01-01 00:25:05   2025-01-01 01:01:10                  N
 ...         ...                  ...                   ...                ...
 48321         2  2025-01-31 19:36:00   2025-01-31 20:05:00               None
 48322         2  2025-01-31 20:33:00   2025-01-31 20:41:00               None
 48323         2  2025-01-31 21:09:00   2025-01-31 21:30:00               None
 48324         2  2025-01-31 22:22:00   2025-01-31 22:25:00               None
 48325         2  2025-01-31 22:15:00   2025-01-31 22:22:00               None

        RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  \
 0             1.0            75           235              1.0           5.93
 1             1.0           166            75              1.0           1.32
 2             5.0           171            73              1.0           0.41
 3             1.0            74           223              1.0           4.12
 4             1.0            66           158              1.0           4.71
 ...           ...           ...           ...              ...            ...
 48321         NaN           179           132              NaN          13.99
 48322         NaN           166            75              NaN           1.51
 48323         NaN            41            42              NaN           2.90
 48324         NaN            75            43              NaN           0.34
 48325         NaN            42           194              NaN           1.37

        fare_amount  ...  mta_tax  tip_amount  tolls_amount  ehail_fee  \
 0            24.70  ...      0.5        6.80          0.00        NaN
 1             8.60  ...      0.5        0.00          0.00        NaN
 2            25.55  ...      0.0        0.00          0.00        NaN
 3            21.20  ...      0.5        6.13          6.94        NaN
 4            33.80  ...      0.5        7.81          0.00        NaN
 ...            ...  ...      ...         ...           ...        ...
 48321        55.61  ...      0.5       11.42          0.00        NaN
 48322        13.58  ...      0.5        2.26          0.00        NaN
 48323        30.89  ...      0.5        0.00          0.00        NaN
 48324        14.78  ...      0.5        2.44          0.00        NaN
 48325        66.67  ...      0.5       10.00          6.94        NaN

        improvement_surcharge  total_amount  payment_type  trip_type  \
 0                        1.0         34.00           1.0        1.0
 1                        1.0         11.10           2.0        1.0
 2                        1.0         26.55           2.0        2.0
 3                        1.0         36.77           1.0        1.0
 4                        1.0         46.86           1.0        1.0
 ...                      ...           ...           ...        ...
 48321                    1.0         68.53           NaN        NaN
 48322                    1.0         17.34           NaN        NaN
 48323                    1.0         32.39           NaN        NaN
 48324                    1.0         18.72           NaN        NaN
 48325                    1.0         85.11           NaN        NaN

        congestion_surcharge  cbd_congestion_fee
 0                      0.00                 0.0
 1                      0.00                 0.0
 2                      0.00                 0.0
 3                      0.00                 0.0
 4                      2.75                 0.0
 ...                     ...                 ...
 48321                   NaN                 NaN
 48322                   NaN                 NaN
 48323                   NaN                 NaN
 48324                   NaN                 NaN
 48325                   NaN                 NaN

 [48326 rows x 21 columns],
        VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  \
 0             2  2025-02-01 00:12:15   2025-02-01 00:15:48                  N
 1             2  2025-01-31 23:57:05   2025-02-01 00:24:24                  N
 2             2  2025-02-01 00:24:26   2025-02-01 00:49:54                  N
 3             1  2025-02-01 00:17:15   2025-02-01 00:25:56                  N
 4             2  2025-02-01 00:17:36   2025-02-01 00:26:36                  N
 ...         ...                  ...                   ...                ...
 46616         2  2025-02-28 22:35:00   2025-02-28 23:10:00               None
 46617         2  2025-02-28 23:40:00   2025-02-28 23:55:00               None
 46618         2  2025-02-28 23:34:00   2025-02-28 23:48:00               None
 46619         2  2025-02-28 23:52:00   2025-03-01 00:05:00               None
 46620         2  2025-02-28 23:04:00   2025-02-28 23:17:00               None

        RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  \
 0             1.0           166            41              1.0           0.65
 1             1.0           255           161              1.0           6.57
 2             1.0            75           182              2.0           8.36
 3             1.0            97           209              1.0           2.40
 4             1.0             7           223              1.0           1.31
 ...           ...           ...           ...              ...            ...
 46616         NaN           181           161              NaN           8.23
 46617         NaN           166           141              NaN           4.10
 46618         NaN            41            48              NaN           4.09
 46619         NaN            75           140              NaN           2.25
 46620         NaN             7           263              NaN           5.52

        fare_amount  ...  mta_tax  tip_amount  tolls_amount  ehail_fee  \
 0             6.50  ...      0.5        1.80          0.00        NaN
 1            31.70  ...      0.5        0.00          0.00        NaN
 2            36.60  ...      0.5        0.00          0.00        NaN
 3            12.80  ...      1.5        3.75          0.00        NaN
 4            10.70  ...      0.5        2.64          0.00        NaN
 ...            ...  ...      ...         ...           ...        ...
 46616        44.39  ...      0.5        7.41          0.00        NaN
 46617        27.67  ...      0.5        6.38          0.00        NaN
 46618        27.71  ...      0.5        0.00          0.00        NaN
 46619        16.64  ...      0.5        1.00          0.00        NaN
 46620        27.38  ...      0.5        7.71          6.94        NaN

        improvement_surcharge  total_amount  payment_type  trip_type  \
 0                        1.0         10.80           1.0        1.0
 1                        1.0         37.70           2.0        1.0
 2                        1.0         39.10           2.0        1.0
 3                        1.0         22.55           1.0        1.0
 4                        1.0         15.84           1.0        1.0
 ...                      ...           ...           ...        ...
 46616                    1.0         56.80           NaN        NaN
 46617                    1.0         38.30           NaN        NaN
 46618                    1.0         32.71           NaN        NaN
 46619                    1.0         21.89           NaN        NaN
 46620                    1.0         46.28           NaN        NaN

        congestion_surcharge  cbd_congestion_fee
 0                      0.00                0.00
 1                      2.75                0.75
 2                      0.00                0.00
 3                      2.75                0.75
 4                      0.00                0.00
 ...                     ...                 ...
 46616                   NaN                0.75
 46617                   NaN                0.00
 46618                   NaN                0.75
 46619                   NaN                0.00
 46620                   NaN                0.00

 [46621 rows x 21 columns]]

In [36]:
type(all_chunks)
data= pd.concat(all_chunks, ignore_index=True)
print(type(data))
data.head()

<class 'pandas.core.frame.DataFrame'>

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-01-01 00:03:01,2025-01-01 00:17:12,N,1.0,75,235,1.0,5.93,24.70,...,0.5,6.80,0.00,NaN,1.0,34.00,1.0,1.0,0.00,0.0
1,2,2025-01-01 00:19:59,2025-01-01 00:25:52,N,1.0,166,75,1.0,1.32,8.60,...,0.5,0.00,0.00,NaN,1.0,11.10,2.0,1.0,0.00,0.0
2,2,2025-01-01 00:05:29,2025-01-01 00:07:21,N,5.0,171,73,1.0,0.41,25.55,...,0.0,0.00,0.00,NaN,1.0,26.55,2.0,2.0,0.00,0.0
3,2,2025-01-01 00:52:24,2025-01-01 01:07:52,N,1.0,74,223,1.0,4.12,21.20,...,0.5,6.13,6.94,NaN,1.0,36.77,1.0,1.0,0.00,0.0
4,2,2025-01-01 00:25:05,2025-01-01 01:01:10,N,1.0,66,158,1.0,4.71,33.80,...,0.5,7.81,0.00,NaN,1.0,46.86,1.0,1.0,2.75,0.0